# Generated by Django 4.2.7 on 2024-04-29 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
