# Generated by Django 4.2.7 on 2024-04-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0002_delete_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='nomenclature',
            new_name='name_shirt',
        ),
        migrations.AddField(
            model_name='person',
            name='shirts',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default=None, max_length=100, null=True),
        ),
    ]
