# Generated by Django 4.2.7 on 2024-04-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_models', '0003_rename_nomenclature_person_name_shirt_person_shirts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name_shirt',
            field=models.CharField(max_length=30, verbose_name='shirts'),
        ),
    ]
