# Generated by Django 4.2.7 on 2024-04-30 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_models', '0006_alter_article_headline_myspecialuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myspecialuser',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
