# Generated by Django 4.2.7 on 2024-04-30 09:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_models', '0007_alter_myspecialuser_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myspecialuser',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='myspecialuser',
            name='supervisor',
            field=models.ManyToManyField(related_name='supervisor_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
